<a href="https://colab.research.google.com/github/alicepearse/DL_prac/blob/master/NLP_text_preprocessing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [21]:
sentences = [
             "I like cherry pie",
             "I love coffee and cookies",
             "I hate onions"
]

In [22]:
# dataset = long sequence of words
# current_idx = 1
# word2idx = {}
# for word in dataset:
#   if word not in word2idx:
#     word2idx[word] = current_idx
#     current_idx += 1

In [23]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [24]:
print(sequences)

[[1, 2, 3, 4], [1, 5, 6, 7, 8], [1, 9, 10]]


In [25]:
tokenizer.word_index

{'and': 7,
 'cherry': 3,
 'coffee': 6,
 'cookies': 8,
 'hate': 9,
 'i': 1,
 'like': 2,
 'love': 5,
 'onions': 10,
 'pie': 4}

In [27]:
MAXLEN = 5
data = pad_sequences(
    sequences,
    maxlen=MAXLEN,
    padding='post'
)

In [28]:
print(data)

[[ 1  2  3  4  0]
 [ 1  5  6  7  8]
 [ 1  9 10  0  0]]
